name: Daily Placement Prep Bot

on:
  schedule:
    # 1:15 PM IST → 07:45 UTC
    - cron: "45 7 * * *"
    # 8:30 PM IST → 15:00 UTC
    - cron: "0 15 * * *"
  workflow_dispatch:  # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py
